"""empty message

Revision ID: a8342798d349
Revises: 
Create Date: 2018-09-29 00:33:13.649729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8342798d349'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comment_post_uuid'), 'comment', ['post_uuid'], unique=False)
    op.drop_index('post_comments_index', table_name='comment')
    op.create_index('ix_post_search_vector', 'post', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=254),
               nullable=False)
    op.alter_column('user', 'salt',
               existing_type=sa.CHAR(length=29),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'salt',
               existing_type=sa.CHAR(length=29),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=254),
               nullable=True)
    op.drop_index('ix_post_search_vector', table_name='post')
    op.create_index('post_comments_index', 'comment', ['post_uuid'], unique=False)
    op.drop_index(op.f('ix_comment_post_uuid'), table_name='comment')
    # ### end Alembic commands ###
